export type SeoPageType = "pSEO City Page" | "Service Hub" | "Blog Post";

export type SeoPage = {
  pageTitle: string;
  pageSlug: string;
  primaryKeyword: string;
  secondaryKeywords: string;
  targetArea: string;
  pageType: SeoPageType;
  searchIntent: string;
  volumePerMonth: string;
  keywordDifficulty: string;
  cpc: string;
  priority: string;
  ctaStrategy: string;
};

export const SITE_NAME = "Gas Line Repair Pros";
export const DEFAULT_SITE_URL = "https://gaslinerepairpros.com";
export const PHONE_DISPLAY = "1-855-318-3325";
export const PHONE_E164 = "+18553183325";

export const SEO_PAGES: SeoPage[] = [
  {
    "pageTitle": "Gas Line Repair in Mississauga, ON",
    "pageSlug": "/gas-line-repair-mississauga",
    "primaryKeyword": "gas line repair mississauga",
    "secondaryKeywords": "gas pipe repair mississauga, gas leak repair mississauga, gas line service near me",
    "targetArea": "Mississauga, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Toronto, ON",
    "pageSlug": "/gas-line-repair-toronto",
    "primaryKeyword": "gas line repair toronto",
    "secondaryKeywords": "gas plumber toronto, gas leak repair toronto, gas line repair near me",
    "targetArea": "Toronto, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Burlington, ON",
    "pageSlug": "/gas-line-repair-burlington",
    "primaryKeyword": "gas line repair burlington",
    "secondaryKeywords": "gas leak repair burlington, gas line service burlington",
    "targetArea": "Burlington, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Hamilton, ON",
    "pageSlug": "/gas-line-repair-hamilton",
    "primaryKeyword": "gas line repair hamilton",
    "secondaryKeywords": "gas leak repair hamilton, gas line installation hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Oakville, ON",
    "pageSlug": "/gas-line-repair-oakville",
    "primaryKeyword": "gas line repair oakville",
    "secondaryKeywords": "gas leak repair oakville, gas pipe repair oakville",
    "targetArea": "Oakville, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Kamloops, BC",
    "pageSlug": "/gas-line-repair-kamloops",
    "primaryKeyword": "gas line repair kamloops",
    "secondaryKeywords": "kamloops gas line repair, gas line service kamloops",
    "targetArea": "Kamloops, BC",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "70.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Etobicoke, ON",
    "pageSlug": "/gas-line-repair-etobicoke",
    "primaryKeyword": "gas line repair etobicoke",
    "secondaryKeywords": "etobicoke gas boiler line repair, gas pipe repair etobicoke",
    "targetArea": "Etobicoke, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Saskatoon, SK",
    "pageSlug": "/gas-line-repair-saskatoon",
    "primaryKeyword": "gas line repair saskatoon",
    "secondaryKeywords": "gas line service saskatoon, gas plumber saskatoon",
    "targetArea": "Saskatoon, SK",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in London, ON",
    "pageSlug": "/gas-line-repair-london",
    "primaryKeyword": "gas line repair london",
    "secondaryKeywords": "gas leak repair london, gas line service london",
    "targetArea": "London, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Repair in Yorkton, SK",
    "pageSlug": "/gas-line-repair-yorkton",
    "primaryKeyword": "gas line repair yorkton",
    "secondaryKeywords": "gas line service yorkton, gas plumber yorkton",
    "targetArea": "Yorkton, SK",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Installation in Toronto, ON",
    "pageSlug": "/gas-line-installation-toronto",
    "primaryKeyword": "gas line installation toronto",
    "secondaryKeywords": "gas pipe installation toronto, gas line installer toronto, gas line near me",
    "targetArea": "Toronto, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1.3",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Calgary, AB",
    "pageSlug": "/gas-line-installation-calgary",
    "primaryKeyword": "gas line installation calgary",
    "secondaryKeywords": "gas fitting calgary, gas line repair calgary, gas pipe installation calgary",
    "targetArea": "Calgary, AB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Mississauga, ON",
    "pageSlug": "/gas-line-installation-mississauga",
    "primaryKeyword": "gas line installation mississauga",
    "secondaryKeywords": "gas pipe installation mississauga, gas line installation near me",
    "targetArea": "Mississauga, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Fitting Services in Calgary, AB",
    "pageSlug": "/gas-fitting-calgary",
    "primaryKeyword": "gas fitting calgary",
    "secondaryKeywords": "gas fitting services calgary, gas line installation calgary, gas plumber calgary",
    "targetArea": "Calgary, AB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "10.0",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Fitting Services in Vancouver, BC",
    "pageSlug": "/gas-fitting-vancouver",
    "primaryKeyword": "gas fitting vancouver",
    "secondaryKeywords": "gas fitting services vancouver, gas line installation vancouver",
    "targetArea": "Vancouver, BC",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.5",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Oakville, ON",
    "pageSlug": "/gas-leak-repair-oakville",
    "primaryKeyword": "gas leak repair oakville",
    "secondaryKeywords": "gas leak detection oakville, gas pipe repair oakville, emergency gas repair",
    "targetArea": "Oakville, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Burlington, ON",
    "pageSlug": "/gas-leak-repair-burlington",
    "primaryKeyword": "gas leak repair burlington",
    "secondaryKeywords": "gas leak detection burlington, gas leak repair near me",
    "targetArea": "Burlington, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Hamilton, ON",
    "pageSlug": "/gas-leak-repair-hamilton",
    "primaryKeyword": "gas leak repair hamilton",
    "secondaryKeywords": "gas leak detection hamilton, gas line repair hamilton",
    "targetArea": "Hamilton, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Vernon, BC",
    "pageSlug": "/gas-leak-repair-vernon",
    "primaryKeyword": "gas leak repair vernon",
    "secondaryKeywords": "gas leak repair service vernon, gas leak detection vernon",
    "targetArea": "Vernon, BC",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "40.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Toronto, ON",
    "pageSlug": "/gas-leak-repair-toronto",
    "primaryKeyword": "gas leak repair toronto",
    "secondaryKeywords": "emergency gas leak repair toronto, gas leak detection toronto",
    "targetArea": "Toronto, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Surrey, BC",
    "pageSlug": "/gas-leak-repair-surrey",
    "primaryKeyword": "gas leak repair surrey",
    "secondaryKeywords": "gas leak detection surrey, gas pipe repair surrey",
    "targetArea": "Surrey, BC",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Port Moody, BC",
    "pageSlug": "/gas-leak-repair-port-moody",
    "primaryKeyword": "gas leak repair services in port moody",
    "secondaryKeywords": "gas leak detection port moody, gas pipe repair port moody",
    "targetArea": "Port Moody, BC",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair Services | GasLineRepairPros",
    "pageSlug": "/gas-line-repair",
    "primaryKeyword": "gas line repair",
    "secondaryKeywords": "gas pipe repair, repair gas line, gas line repair near me, gas line repair cost",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial + Informational",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.5",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Detection Services | GasLineRepairPros",
    "pageSlug": "/gas-leak-detection",
    "primaryKeyword": "gas leak detection",
    "secondaryKeywords": "gas leak detection company, gas leak detection near me, natural gas leak detection",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial + Informational",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation Services | GasLineRepairPros",
    "pageSlug": "/gas-line-installation",
    "primaryKeyword": "gas line installation",
    "secondaryKeywords": "gas line installation near me, gas pipe installation, bbq gas line installation, exterior gas line installation",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.5",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Fitting Services | GasLineRepairPros",
    "pageSlug": "/gas-fitting-services",
    "primaryKeyword": "gas fitting services",
    "secondaryKeywords": "gas fitting, gas fitting near me, gas fitting contractor",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.0",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Appliance Installation | GasLineRepairPros",
    "pageSlug": "/gas-appliance-installation",
    "primaryKeyword": "gas appliance installation",
    "secondaryKeywords": "gas hookup, gas line installer, gas line installation near me",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.0",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair Services | GasLineRepairPros",
    "pageSlug": "/gas-leak-repair",
    "primaryKeyword": "gas leak repair",
    "secondaryKeywords": "gas leak repair near me, emergency gas leak repair, gas line leak repair",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial",
    "volumePerMonth": "100.0",
    "keywordDifficulty": "0.0",
    "cpc": "4.0",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "BBQ Gas Line Installation | GasLineRepairPros",
    "pageSlug": "/bbq-gas-line-installation",
    "primaryKeyword": "bbq gas line installation",
    "secondaryKeywords": "bbq gas line, exterior gas line installation, outdoor gas line",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "0.0",
    "cpc": "1.6",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325 + Get a Quote"
  },
  {
    "pageTitle": "Gas Line Inspection Services | GasLineRepairPros",
    "pageSlug": "/gas-line-inspection",
    "primaryKeyword": "gas line inspection",
    "secondaryKeywords": "gas line service, gas pipe inspection, natural gas inspection",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Commercial + Informational",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "1.7",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Emergency Gas Leak Repair | GasLineRepairPros",
    "pageSlug": "/emergency-gas-leak-repair",
    "primaryKeyword": "emergency gas leak repair",
    "secondaryKeywords": "gas leak repair near me, 24/7 gas repair, gas leak plumber",
    "targetArea": "National",
    "pageType": "Service Hub",
    "searchIntent": "Transactional",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "What Does a Gas Leak Smell Like? Complete Guide",
    "pageSlug": "/blog/what-does-a-gas-leak-smell-like",
    "primaryKeyword": "what does a gas leak smell like",
    "secondaryKeywords": "gas leak smell, what does gas leak smell like, smell of gas leak",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "400.0",
    "keywordDifficulty": "5.0",
    "cpc": "0.06",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Natural Gas Leak Symptoms: Signs to Never Ignore",
    "pageSlug": "/blog/natural-gas-leak-symptoms",
    "primaryKeyword": "natural gas leak symptoms",
    "secondaryKeywords": "gas leak symptoms, signs of a gas leak, natural gas leak, gas leak warning signs",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "150.0",
    "keywordDifficulty": "10.0",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Symptoms: How to Know If You Have a Leak",
    "pageSlug": "/blog/gas-leak-symptoms",
    "primaryKeyword": "gas leak symptoms",
    "secondaryKeywords": "gas leak smell, what does a gas leak smell like, natural gas leak symptoms",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "7.0",
    "cpc": "1.1",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Smell: What It Means & What to Do",
    "pageSlug": "/blog/gas-leak-smell",
    "primaryKeyword": "gas leak smell",
    "secondaryKeywords": "what does a gas leak smell like, gas smell in house, smell gas at home",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "300.0",
    "keywordDifficulty": "3.0",
    "cpc": "0.7",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Best Gas Leak Detectors for Canadian Homes (2025)",
    "pageSlug": "/blog/best-gas-leak-detector",
    "primaryKeyword": "gas leak detector",
    "secondaryKeywords": "natural gas leak detector, portable gas leak detectors, home gas detector",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational + Commercial",
    "volumePerMonth": "700.0",
    "keywordDifficulty": "0.0",
    "cpc": "0.45",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "How Much Does Gas Line Repair Cost in Canada?",
    "pageSlug": "/blog/gas-line-repair-cost",
    "primaryKeyword": "gas line repair cost",
    "secondaryKeywords": "gas leak repair cost, gas line leak repair cost, gas pipe repair pricing",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "60.0",
    "keywordDifficulty": "-",
    "cpc": "2.5",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "What Is Gas Fitting? Everything Homeowners Need to Know",
    "pageSlug": "/blog/what-is-gas-fitting",
    "primaryKeyword": "gas fitting",
    "secondaryKeywords": "gas fitting services, gas fitter near me, what does a gas fitter do",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "250.0",
    "keywordDifficulty": "0.0",
    "cpc": "2.5",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Natural Gas Leak: What to Do & Who to Call",
    "pageSlug": "/blog/natural-gas-leak-what-to-do",
    "primaryKeyword": "natural gas leak",
    "secondaryKeywords": "gas leak symptoms, gas leak smell, what to do gas leak, natural gas leak detection",
    "targetArea": "National",
    "pageType": "Blog Post",
    "searchIntent": "Informational",
    "volumePerMonth": "200.0",
    "keywordDifficulty": "7.0",
    "cpc": "0.6",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Scarborough, ON",
    "pageSlug": "/gas-line-repair-scarborough",
    "primaryKeyword": "gas line repair scarborough",
    "secondaryKeywords": "gas pipe repair scarborough, gas leak repair scarborough, gas line service scarborough",
    "targetArea": "Scarborough, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in North York, ON",
    "pageSlug": "/gas-line-repair-north-york",
    "primaryKeyword": "gas line repair north york",
    "secondaryKeywords": "gas pipe repair north york, gas leak repair north york, gas plumber north york",
    "targetArea": "North York, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Brampton, ON",
    "pageSlug": "/gas-line-repair-brampton",
    "primaryKeyword": "gas line repair brampton",
    "secondaryKeywords": "gas pipe repair brampton, gas leak repair brampton, gas plumber brampton",
    "targetArea": "Brampton, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Markham, ON",
    "pageSlug": "/gas-line-repair-markham",
    "primaryKeyword": "gas line repair markham",
    "secondaryKeywords": "gas pipe repair markham, gas leak repair markham, gas line service markham",
    "targetArea": "Markham, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Vaughan, ON",
    "pageSlug": "/gas-line-repair-vaughan",
    "primaryKeyword": "gas line repair vaughan",
    "secondaryKeywords": "gas pipe repair vaughan, gas fitting vaughan, gas plumber vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Richmond Hill, ON",
    "pageSlug": "/gas-line-repair-richmond-hill",
    "primaryKeyword": "gas line repair richmond hill",
    "secondaryKeywords": "richmond hill gas boiler line repair, gas pipe repair richmond hill",
    "targetArea": "Richmond Hill, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Pickering, ON",
    "pageSlug": "/gas-line-repair-pickering",
    "primaryKeyword": "gas line repair pickering",
    "secondaryKeywords": "gas leak repair pickering, gas pipe repair pickering, gas plumber pickering",
    "targetArea": "Pickering, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Ajax, ON",
    "pageSlug": "/gas-line-repair-ajax",
    "primaryKeyword": "gas line repair ajax",
    "secondaryKeywords": "ajax gas boiler line repair services, gas leak repair ajax, gas plumber ajax",
    "targetArea": "Ajax, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Whitby, ON",
    "pageSlug": "/gas-line-repair-whitby",
    "primaryKeyword": "gas line repair whitby",
    "secondaryKeywords": "gas pipe repair whitby, gas leak repair whitby, gas plumber whitby",
    "targetArea": "Whitby, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Oshawa, ON",
    "pageSlug": "/gas-line-repair-oshawa",
    "primaryKeyword": "gas line repair oshawa",
    "secondaryKeywords": "gas leak repair oshawa, gas pipe repair oshawa, gas plumber oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Newmarket, ON",
    "pageSlug": "/gas-line-repair-newmarket",
    "primaryKeyword": "gas line repair newmarket",
    "secondaryKeywords": "gas pipe repair newmarket, gas fitting newmarket, gas plumber newmarket",
    "targetArea": "Newmarket, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Aurora, ON",
    "pageSlug": "/gas-line-repair-aurora",
    "primaryKeyword": "gas line repair aurora",
    "secondaryKeywords": "gas pipe repair aurora, gas leak repair aurora, gas plumber aurora",
    "targetArea": "Aurora, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Thornhill, ON",
    "pageSlug": "/gas-line-repair-thornhill",
    "primaryKeyword": "gas line repair thornhill",
    "secondaryKeywords": "gas pipe repair thornhill, gas leak repair thornhill, gas fitting thornhill",
    "targetArea": "Thornhill, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Woodbridge, ON",
    "pageSlug": "/gas-line-repair-woodbridge",
    "primaryKeyword": "gas line repair woodbridge",
    "secondaryKeywords": "gas pipe repair woodbridge, gas fitting woodbridge, gas plumber woodbridge",
    "targetArea": "Woodbridge, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in East York, ON",
    "pageSlug": "/gas-line-repair-east-york",
    "primaryKeyword": "gas line repair east york",
    "secondaryKeywords": "gas pipe repair east york, gas leak repair east york, gas plumber east york",
    "targetArea": "East York, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Stouffville, ON",
    "pageSlug": "/gas-line-repair-stouffville",
    "primaryKeyword": "gas line repair stouffville",
    "secondaryKeywords": "gas pipe repair stouffville, gas leak repair stouffville, gas plumber stouffville",
    "targetArea": "Stouffville, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Brampton, ON",
    "pageSlug": "/gas-line-installation-brampton",
    "primaryKeyword": "gas line installation brampton",
    "secondaryKeywords": "gas pipe installation brampton, gas line installer brampton, bbq gas line brampton",
    "targetArea": "Brampton, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Markham, ON",
    "pageSlug": "/gas-line-installation-markham",
    "primaryKeyword": "gas line installation markham",
    "secondaryKeywords": "markham gas boiler line repair services, gas pipe installation markham",
    "targetArea": "Markham, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "20.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Vaughan, ON",
    "pageSlug": "/gas-line-installation-vaughan",
    "primaryKeyword": "gas line installation vaughan",
    "secondaryKeywords": "gas pipe installation vaughan, gas fitting vaughan, gas line installer vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Richmond Hill, ON",
    "pageSlug": "/gas-line-installation-richmond-hill",
    "primaryKeyword": "gas line installation richmond hill",
    "secondaryKeywords": "richmond hill gas boiler line repair, gas pipe installation richmond hill",
    "targetArea": "Richmond Hill, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "30.0",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Scarborough, ON",
    "pageSlug": "/gas-line-installation-scarborough",
    "primaryKeyword": "gas line installation scarborough",
    "secondaryKeywords": "gas pipe installation scarborough, gas appliance installation scarborough",
    "targetArea": "Scarborough, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in North York, ON",
    "pageSlug": "/gas-line-installation-north-york",
    "primaryKeyword": "gas line installation north york",
    "secondaryKeywords": "gas pipe installation north york, gas line installer north york",
    "targetArea": "North York, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Pickering, ON",
    "pageSlug": "/gas-line-installation-pickering",
    "primaryKeyword": "gas line installation pickering",
    "secondaryKeywords": "gas pipe installation pickering, gas appliance installation pickering",
    "targetArea": "Pickering, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Oshawa, ON",
    "pageSlug": "/gas-line-installation-oshawa",
    "primaryKeyword": "gas line installation oshawa",
    "secondaryKeywords": "gas pipe installation oshawa, gas line installer oshawa, gas appliance installation oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Newmarket, ON",
    "pageSlug": "/gas-line-installation-newmarket",
    "primaryKeyword": "gas line installation newmarket",
    "secondaryKeywords": "gas pipe installation newmarket, gas line installer newmarket",
    "targetArea": "Newmarket, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Scarborough, ON",
    "pageSlug": "/gas-leak-repair-scarborough",
    "primaryKeyword": "gas leak repair scarborough",
    "secondaryKeywords": "gas leak detection scarborough, emergency gas repair scarborough",
    "targetArea": "Scarborough, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in North York, ON",
    "pageSlug": "/gas-leak-repair-north-york",
    "primaryKeyword": "gas leak repair north york",
    "secondaryKeywords": "gas leak detection north york, emergency gas repair north york",
    "targetArea": "North York, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Brampton, ON",
    "pageSlug": "/gas-leak-repair-brampton",
    "primaryKeyword": "gas leak repair brampton",
    "secondaryKeywords": "gas leak detection brampton, emergency gas repair brampton",
    "targetArea": "Brampton, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Vaughan, ON",
    "pageSlug": "/gas-leak-repair-vaughan",
    "primaryKeyword": "gas leak repair vaughan",
    "secondaryKeywords": "gas leak detection vaughan, emergency gas repair vaughan",
    "targetArea": "Vaughan, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Markham, ON",
    "pageSlug": "/gas-leak-repair-markham",
    "primaryKeyword": "gas leak repair markham",
    "secondaryKeywords": "gas leak detection markham, emergency gas repair markham",
    "targetArea": "Markham, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Richmond Hill, ON",
    "pageSlug": "/gas-leak-repair-richmond-hill",
    "primaryKeyword": "gas leak repair richmond hill",
    "secondaryKeywords": "gas leak detection richmond hill, emergency gas repair richmond hill",
    "targetArea": "Richmond Hill, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Pickering, ON",
    "pageSlug": "/gas-leak-repair-pickering",
    "primaryKeyword": "gas leak repair pickering",
    "secondaryKeywords": "gas leak detection pickering, emergency gas repair pickering",
    "targetArea": "Pickering, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Ajax, ON",
    "pageSlug": "/gas-leak-repair-ajax",
    "primaryKeyword": "gas leak repair ajax",
    "secondaryKeywords": "gas leak detection ajax, emergency gas repair ajax",
    "targetArea": "Ajax, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Oshawa, ON",
    "pageSlug": "/gas-leak-repair-oshawa",
    "primaryKeyword": "gas leak repair oshawa",
    "secondaryKeywords": "gas leak detection oshawa, emergency gas repair oshawa",
    "targetArea": "Oshawa, ON",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Winnipeg, MB",
    "pageSlug": "/gas-line-repair-winnipeg",
    "primaryKeyword": "gas line repair winnipeg",
    "secondaryKeywords": "gas pipe repair winnipeg, gas leak repair winnipeg, gas plumber winnipeg, gas line service winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Brandon, MB",
    "pageSlug": "/gas-line-repair-brandon",
    "primaryKeyword": "gas line repair brandon",
    "secondaryKeywords": "gas pipe repair brandon, gas leak repair brandon, gas plumber brandon",
    "targetArea": "Brandon, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Steinbach, MB",
    "pageSlug": "/gas-line-repair-steinbach",
    "primaryKeyword": "gas line repair steinbach",
    "secondaryKeywords": "gas pipe repair steinbach, gas leak repair steinbach, gas plumber steinbach",
    "targetArea": "Steinbach, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Portage la Prairie, MB",
    "pageSlug": "/gas-line-repair-portage-la-prairie",
    "primaryKeyword": "gas line repair portage la prairie",
    "secondaryKeywords": "gas pipe repair portage la prairie, gas leak repair portage, gas plumber portage",
    "targetArea": "Portage la Prairie, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Selkirk, MB",
    "pageSlug": "/gas-line-repair-selkirk",
    "primaryKeyword": "gas line repair selkirk",
    "secondaryKeywords": "gas pipe repair selkirk, gas leak repair selkirk, gas plumber selkirk",
    "targetArea": "Selkirk, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Winkler, MB",
    "pageSlug": "/gas-line-repair-winkler",
    "primaryKeyword": "gas line repair winkler",
    "secondaryKeywords": "gas pipe repair winkler, gas leak repair winkler, gas plumber winkler",
    "targetArea": "Winkler, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Morden, MB",
    "pageSlug": "/gas-line-repair-morden",
    "primaryKeyword": "gas line repair morden",
    "secondaryKeywords": "gas pipe repair morden, gas leak repair morden, gas plumber morden",
    "targetArea": "Morden, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Dauphin, MB",
    "pageSlug": "/gas-line-repair-dauphin",
    "primaryKeyword": "gas line repair dauphin",
    "secondaryKeywords": "gas pipe repair dauphin, gas leak repair dauphin, gas plumber dauphin",
    "targetArea": "Dauphin, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Thompson, MB",
    "pageSlug": "/gas-line-repair-thompson",
    "primaryKeyword": "gas line repair thompson",
    "secondaryKeywords": "gas pipe repair thompson, gas leak repair thompson, gas plumber thompson",
    "targetArea": "Thompson, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Repair in Stonewall, MB",
    "pageSlug": "/gas-line-repair-stonewall",
    "primaryKeyword": "gas line repair stonewall",
    "secondaryKeywords": "gas pipe repair stonewall, gas leak repair stonewall, gas plumber stonewall",
    "targetArea": "Stonewall, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Winnipeg, MB",
    "pageSlug": "/gas-line-installation-winnipeg",
    "primaryKeyword": "gas line installation winnipeg",
    "secondaryKeywords": "gas pipe installation winnipeg, gas line installer winnipeg, bbq gas line winnipeg, gas appliance installation winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Brandon, MB",
    "pageSlug": "/gas-line-installation-brandon",
    "primaryKeyword": "gas line installation brandon",
    "secondaryKeywords": "gas pipe installation brandon, gas line installer brandon, gas appliance installation brandon",
    "targetArea": "Brandon, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Line Installation in Steinbach, MB",
    "pageSlug": "/gas-line-installation-steinbach",
    "primaryKeyword": "gas line installation steinbach",
    "secondaryKeywords": "gas pipe installation steinbach, gas appliance installation steinbach",
    "targetArea": "Steinbach, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Fitting Services in Winnipeg, MB",
    "pageSlug": "/gas-fitting-winnipeg",
    "primaryKeyword": "gas fitting winnipeg",
    "secondaryKeywords": "gas fitting services winnipeg, gas line installation winnipeg, gas plumber winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Fitting Services in Brandon, MB",
    "pageSlug": "/gas-fitting-brandon",
    "primaryKeyword": "gas fitting brandon",
    "secondaryKeywords": "gas fitting services brandon, gas line installation brandon, gas plumber brandon",
    "targetArea": "Brandon, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Winnipeg, MB",
    "pageSlug": "/gas-leak-repair-winnipeg",
    "primaryKeyword": "gas leak repair winnipeg",
    "secondaryKeywords": "gas leak detection winnipeg, emergency gas leak repair winnipeg, gas pipe repair winnipeg",
    "targetArea": "Winnipeg, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P1",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Brandon, MB",
    "pageSlug": "/gas-leak-repair-brandon",
    "primaryKeyword": "gas leak repair brandon",
    "secondaryKeywords": "gas leak detection brandon, emergency gas repair brandon",
    "targetArea": "Brandon, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P2",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Steinbach, MB",
    "pageSlug": "/gas-leak-repair-steinbach",
    "primaryKeyword": "gas leak repair steinbach",
    "secondaryKeywords": "gas leak detection steinbach, emergency gas repair steinbach",
    "targetArea": "Steinbach, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Portage la Prairie, MB",
    "pageSlug": "/gas-leak-repair-portage-la-prairie",
    "primaryKeyword": "gas leak repair portage la prairie",
    "secondaryKeywords": "gas leak detection portage, emergency gas repair portage la prairie",
    "targetArea": "Portage la Prairie, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  },
  {
    "pageTitle": "Gas Leak Repair in Selkirk, MB",
    "pageSlug": "/gas-leak-repair-selkirk",
    "primaryKeyword": "gas leak repair selkirk",
    "secondaryKeywords": "gas leak detection selkirk, emergency gas repair selkirk",
    "targetArea": "Selkirk, MB",
    "pageType": "pSEO City Page",
    "searchIntent": "Commercial + Local",
    "volumePerMonth": "<10",
    "keywordDifficulty": "-",
    "cpc": "-",
    "priority": "P3",
    "ctaStrategy": "Call 1-855-318-3325"
  }
] as SeoPage[];

export const CITY_PAGES = SEO_PAGES.filter((page) => page.pageType === "pSEO City Page");
export const SERVICE_HUBS = SEO_PAGES.filter((page) => page.pageType === "Service Hub");
export const BLOG_POSTS = SEO_PAGES.filter((page) => page.pageType === "Blog Post");

export function toPath(slug: string) {
  return slug.startsWith("/") ? slug : `/${slug}`;
}

export function stripPath(pathname: string) {
  return pathname.replace(/^\/+/, "").replace(/\/+$/, "");
}

export function getSiteUrl() {
  return process.env.NEXT_PUBLIC_SITE_URL || DEFAULT_SITE_URL;
}

export function absoluteUrl(path: string) {
  return `${getSiteUrl()}${path}`;
}

export function bySlug(slugSegment: string) {
  return SEO_PAGES.find((page) => stripPath(page.pageSlug) === stripPath(slugSegment)) ?? null;
}

export function cityFromTargetArea(targetArea: string) {
  return targetArea.split(",")[0]?.trim() || targetArea;
}

export function serviceTopic(page: SeoPage) {
  const lowered = page.pageTitle.toLowerCase();
  if (lowered.includes("gas leak")) return "Gas Leak Repair";
  if (lowered.includes("gas fitting")) return "Gas Fitting Services";
  if (lowered.includes("installation")) return "Gas Line Installation";
  if (lowered.includes("detection")) return "Gas Leak Detection";
  return "Gas Line Repair";
}

export function relatedPages(page: SeoPage, limit = 12) {
  const topic = serviceTopic(page);
  return CITY_PAGES.filter((item) => item.pageSlug !== page.pageSlug && serviceTopic(item) === topic).slice(0, limit);
}
